# -*- coding: utf-8 -*-
"""Video.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YLDBNsfTT-7b5ti-D3-XHnqG40Af0oxW
"""

import os
from gtts import gTTS
myText="Alerta"
output=gTTS(text=myText,lang="es",slow=False)
output.save("Aviso.mp3")
os.system("mpg123 Aviso.mp3")
